---

- name: Inspect container image
  community.general.docker_image_info:
    name: '{{ built_image.name }}:{{ built_image.tag }}'
  register: image_info
  become: '{{ need_become }}'

- name: Check image existence
  ansible.builtin.assert:
    that:
      - image_info.images

- name: Start container
  community.general.docker_container:
    image: '{{ built_image.name }}:{{ built_image.tag }}'
    name: '{{ deploy.container_name }}'
    state: started
    container_default_behavior: 'no_defaults'
    auto_remove: 'no'
    detach: 'yes'
    init: 'no'
    interactive: 'no'
    memory: '0'
    paused: 'no'
    privileged: 'no'
    read_only: 'no'
    tty: 'no'
    ports:
      - '{{ deploy.exposed_port }}:8080'
  become: '{{ need_become }}'
