---

- name: Install Python dependencies
  pip:
    name:
      - docker  # To build and start containers
      - requests  # To handle HTTP requests while testing
    extra_args: '{{ pip_extra_args }}'
  become: '{{ need_become }}'
