---

- name: Install Python dependencies
  pip:
    name:
      - docker  # To build and start containers
      - requests  # To handle HTTP requests while testing
    state: 'latest'
  become: 'yes'
