---

- name: Create temporary file
  tempfile:
    prefix: ""
    suffix: ".py"
  register: tmpfile
  notify:
    - Delete temporary file

- name: Generate test script
  template:
    src: http_get_test.py.j2
    dest: '{{ tmpfile.path }}'
    mode: '0400'

- name: Test server deployment
  script:
  args:
    executable: python3
    cmd: '{{ tmpfile.path }}'
  register: test_results
  ignore_errors: '{{ ignore_errors | default(false) }}'
  no_log: '{{ no_log | default(false) }}' 

- name: Flush temporary file deletion handler
  meta: flush_handlers

- name: Exit early if test succeeded
  meta: end_host
  when:
    - end_host is defined
    - end_host == true
    - test_results.rc is defined
    - test_results.rc == 0
